### ISSUE TITLE
Grid of hyperparameters

### ISSUE THREAD

**Issue by danibene** [aminought/multimodal-telephone-sa#1]
Hello, 

I am having trouble locating the range of values that were considered for optimizing the hyperparameters in [your paper](https://link.springer.com/chapter/10.1007/978-3-030-11027-7_9). Could you please direct me to where I can find this in the repository?

Thank you,

Danielle

**Comment by aminought** [comment]
@danibene Hi! More than 4 years have passed, I have already managed to change my profession... If I understand and remember correctly, you can find it in functions named `*_gs()` in `/src/models/*/*.py`.

**Comment by danibene** [comment]
@aminought ah, found them now e.g.:
https://github.com/aminought/multimodal-telephone-sa/blob/06bd3ac20a145d74a8398bcd28ad56b6e77d8c21/src/models/audio/acoustic.py#L24-L27

Really appreciate your response!
